owner: get6pm
repo: uptime

sites:
  - name: API
    url: https://api.get6pm.com/v1/health
    expectedStatusCodes:
      - 200
    assignees:
      - duongdev
      - bkdev98
  - name: Private Docs
    url: https://docs.rp.get6pm.com
    assignees:
      - duongdev
  - name: CRM
    url: https://20.rp.get6pm.com
    assignees:
      - duongdev

status-website:
  cname: status.get6pm.com
  logoUrl: https://raw.githubusercontent.com/get6pm/uptime/refs/heads/master/assets/6pm-dark.svg
  faviconSvg: https://raw.githubusercontent.com/get6pm/uptime/refs/heads/master/assets/6pm-dark.svg
  name: 6pm Status
  introTitle: "**6pm** is the open-source expense management platform."
  introMessage: "Check the status of 6pm's API and services."
  navbar:
    - title: Get 6pm
      href: https://get6pm.com?utm_source=status&utm_medium=navbar
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/6pm

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
